src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_u;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeArticle", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_article;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Section", inversedBy="articles")
     */
    private $sections;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\QuantiteTaille", mappedBy="article", cascade={"persist"})
     */
    private $quantite_tailles;

    public function __construct()
    {
        $this->sections = new ArrayCollection();
        $this->lignes_de_commande = new ArrayCollection();
        $this->quantite_tailles = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixU(): ?float
    {
        return $this->prix_u;
    }

    public function setPrixU(float $prix_u): self
    {
        $this->prix_u = $prix_u;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTypeArticle(): ?TypeArticle
    {
        return $this->type_article;
    }

    public function setTypeArticle(?TypeArticle $type_article): self
    {
        $this->type_article = $type_article;

        return $this;
    }

    /**
     * @return Collection|Section[]
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): self
    {
        if (!$this->sections->contains($section)) {
            $this->sections[] = $section;
        }

        return $this;
    }

    public function removeSection(Section $section): self
    {
        if ($this->sections->contains($section)) {
            $this->sections->removeElement($section);
        }

        return $this;
    }

    /**
     * @return Collection|QuantiteTaille[]
     */
    public function getQuantiteTailles(): Collection
    {
        return $this->quantite_tailles;
    }

    public function addQuantiteTaille(QuantiteTaille $quantite_tailles): self
    {
        if (!$this->quantite_tailles->contains($quantite_tailles)) {
            $this->quantite_tailles[] = $quantite_tailles;
            $quantite_tailles->setArticle($this);
        }

        return $this;
    }

    public function removeQuantiteTaille(QuantiteTaille $quantite_tailles): self
    {
        if ($this->quantite_tailles->contains($quantite_tailles)) {
            $this->quantite_tailles->removeElement($quantite_tailles);
            // set the owning side to null (unless already changed)
            if ($quantite_tailles->getArticle() === $this) {
                $quantite_tailles->setArticle(null);
            }
        }

        return $this;
    }

}

src/Entity/Panier.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PanierRepository")
 */
class Panier
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $client_id;

    /**
     * @ORM\Column(type="array")
     */
    private $panier = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->client_id;
    }

    public function setClientId(int $client_id): self
    {
        $this->client_id = $client_id;

        return $this;
    }

    public function getPanier(): ?array
    {
        return $this->panier;
    }

    public function setPanier(array $panier): self
    {
        $this->panier = $panier;

        return $this;
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use App\Service\Panier\PanierService;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Entity\Article;

class PanierController extends AbstractController
{
    /**
     * @Route("/panier", name="panier")
     */
    public function index(SessionInterface $session, PanierService $panierService)
    {
        return $this->render('panier/index.html.twig', [
            'controller_name' => 'PanierController',
            'panier' => $panierService->getPanier(),
            'total' => $panierService->getTotal(),
        ]);
    }

    /**
     * @Route("/panier/add/{id}", name="panier_add")
     */
    public function add($id, Request $request, PanierService $panierService)
    {
        $idTaille = $request->query->get('taille');
        $quantite = $request->query->get('quantite');
        $quantite = (($quantite && is_numeric($quantite)) ? $quantite : 1);

        $article = $this->getDoctrine()
            ->getRepository(Article::class)
            ->find($id);

        foreach($article->getQuantiteTailles() as $quantiteTaille){
            if($quantiteTaille->getTaille()->getId() == $idTaille){
                if($quantiteTaille->getQte() < ($panierService->getQteFor($id, $idTaille) + $quantite)){
                    return new Response('Pas assez de quantité pour l\'article',282);
                }
            }
        }

        $size = $panierService->add($id, $idTaille, $quantite);

        // return $this->redirectToRoute('article');
        return new JsonResponse(['size' => $size]);
    }

        /**
     * @Route("/panier/modify/{id}", name="panier_modify")
     */
    public function modify($id, Request $request, PanierService $panierService)
    {
        $idTaille = $request->query->get('taille');
        $quantite = $request->query->get('quantite');
        $quantite = (($quantite && is_numeric($quantite)) ? $quantite : 1);

        $size = $panierService->modify($id, $idTaille, $quantite);

        // return $this->redirectToRoute('article');
        return $this->redirectToRoute('panier');
    }

    /**
     * @Route("/panier/remove/{id}", name="panier_remove")
     */
    public function remove($id, Request $request, PanierService $panierService)
    {
        $idTaille = $request->query->get('taille');
        $panierService->remove($id, $idTaille);

        return $this->redirectToRoute('panier');
    }

    /**
     * @Route("/panier/size", name="panier_size")
     */
    public function size(PanierService $panierService)
    {
        $size = $panierService->getNbArticles();

        return new JsonResponse(['size' => $size]);
    }

    /**
     * @Route("/panier/test", name="panier_test")
     */
    public function test(PanierService $panierService)
    {
        $panier = $panierService->getPanierTest2();

        dd($panier);
    }
}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PanierController!{% endblock %}
{% block stylesheets %} <link rel="stylesheet" href="/css/panier.css"/>{% endblock %}

{% block body %}
    <h1 class="h1">PANIER D'ACHATS</h1>
    <div class="panier container">

        {% if panier|length > 0 %}
            <table class="table">
                <thead>
                <tr>
                    <th>Article</th>
                    <th>Taille</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total</th>
                </tr>
                </thead>
                <tbody>
                {% for ligne in panier %}
                    <tr>
                        <td><img src={{ ligne.article.getImage }} alt="article">{{ ligne.article.libelle }}</td>
                        <td class="align-middle">{{ ligne.taille.libelle }}</td>
                        <td class="align-middle">{{ ligne.article.getPrixU }}$</td>
                        <td class="align-middle">
                            <select class="qte-article">
                                {% for quantiteTaille in ligne.article.quantiteTailles %}
                                    {% if quantiteTaille.taille.id == ligne.taille.id %}
                                        {% for i in 1..quantiteTaille.qte %}
                                            {% if i == ligne.quantite %}
                                                <option value="{{ i }}" selected>{{ i }}</option>
                                            {% else %}
                                                <option value="{{ i }}">{{ i }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </td>
                        <td class="align-middle">{{ ligne.article.getPrixU * ligne.quantite }}$</td>
                        <td class="align-middle">
                            <a href="{{ path('panier_remove', {id: ligne.article.id, taille: ligne.taille.id}) }}">Supprimer</a>
                            <input type="hidden" value="{{ ligne.article.id }}" id="id-article"/>
                            <input type="hidden" value="{{ ligne.taille.id }}" id="id-taille"/>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <td colspan="4" class="text-right">Total :</td>
                <td>{{ total }}$</td>
                <td><button class="btn btn-outline-dark" onclick="window.location.href='/commande'">passer la commande</button></td>
                </tfoot>
            </table>
        {% else %}
            Panier Vide !
        {% endif %}
    </div>
{% endblock %}
{% block javascripts %}<script src="/js/panier.js"></script>{% endblock %}