src/Entity/Client.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 * @UniqueEntity(fields="email", message="Email déjà prise")
 */
class Client implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
 
    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Adresse", mappedBy="client", cascade={"persist", "remove"})
     */
    private $adresses;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="client")
     */
    private $commandes;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @Assert\Length(max=4096)
     */
    private $plain_password;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $confirmation_token;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $password_token;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Adresse[]
     */
    public function getAdresses(): ?Collection
    {
        return $this->adresses;
    }

    public function addAdresse(Adresse $adresse): self
    {
        if(!$this->adresses){
            $this->adresses = [];
        }
        if (!$this->adresses->contains($adresse)) {
            $this->adresses[] = $adresse;
            $adresse->setClient($this);
        }

        return $this;
    }

    public function removeAdresse(Adresse $adresse): self
    {
        if ($this->adresses->contains($adresse)) {
            $this->adresses->removeElement($adresse);
            // set the owning side to null (unless already changed)
            if ($adresse->getClient() === $this) {
                $adresse->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setClient($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getClient() === $this) {
                $commande->setClient(null);
            }
        }

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }


    /**
     * @see UserInterface
     */
    public function getPlainPassword(): string
    {
        return (string) $this->plain_password;
    }

    public function setPlainPassword(string $plain_password): self
    {
        $this->plain_password = $plain_password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }


    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmation_token;
    }

    public function setConfirmationToken(?string $confirmation_token): self
    {
        $this->confirmation_token = $confirmation_token;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getPasswordToken(): ?string
    {
        return $this->password_token;
    }

    public function setPasswordToken(?string $password_token): self
    {
        $this->password_token = $password_token;

        return $this;
    }
}

src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneDeCommande", mappedBy="commande", cascade={"persist"})
     */
    private $lignes_de_commande;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ModePaiement")
     * @ORM\JoinColumn(nullable=false)
     */
    private $mode_paiement;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\StatutCommande")
     * @ORM\JoinColumn(nullable=false)
     */
    private $statut_commande;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Adresse")
     * @ORM\JoinColumn(nullable=false)
     */
    private $adresse;

    /**
     * @ORM\Column(type="float")
     */
    private $frais_de_port;

    public function __construct()
    {
        $this->lignes_de_commande = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection|LigneDeCommande[]
     */
    public function getLignesDeCommande(): Collection
    {
        return $this->lignes_de_commande;
    }

    public function addLigneDeCommande(LigneDeCommande $ligneDeCommande): self
    {
        if (!$this->lignes_de_commande->contains($ligneDeCommande)) {
            $this->lignes_de_commande[] = $ligneDeCommande;
            $ligneDeCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneDeCommande(LigneDeCommande $ligneDeCommande): self
    {
        if ($this->lignes_de_commande->contains($ligneDeCommande)) {
            $this->lignes_de_commande->removeElement($ligneDeCommande);
            // set the owning side to null (unless already changed)
            if ($ligneDeCommande->getCommande() === $this) {
                $ligneDeCommande->setCommande(null);
            }
        }

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getModePaiement(): ?ModePaiement
    {
        return $this->mode_paiement;
    }

    public function setModePaiement(?ModePaiement $mode_paiement): self
    {
        $this->mode_paiement = $mode_paiement;

        return $this;
    }

    public function getPrixTotal()
    {
        $total = 0;
        foreach($this->lignes_de_commande as $ligne_de_commande){
            $total += $ligne_de_commande->getMontant();
        }
        return $total;
    }

    public function getNbArticles()
    {
        $total = 0;
        foreach($this->lignes_de_commande as $ligne_de_commande){
            $total += $ligne_de_commande->getQte();
        }
        return $total;
    }

    public function getStatutCommande(): ?StatutCommande
    {
        return $this->statut_commande;
    }

    public function setStatutCommande(?StatutCommande $statut_commande): self
    {
        $this->statut_commande = $statut_commande;

        return $this;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->adresse;
    }

    public function setAdresse(?Adresse $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getFraisDePort(): ?float
    {
        return $this->frais_de_port;
    }

    public function setFraisDePort(float $frais_de_port): self
    {
        $this->frais_de_port = $frais_de_port;

        return $this;
    }

    public function getPrixTotalWithShipping()
    {
        return $this->getPrixTotal() + $this->getFraisDePort();
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Commande;
use App\Entity\Adresse;
use App\Form\AdresseType;
use App\Form\EditClientType;

class ClientController extends AbstractController
{
    /**
     * @Route("/compte", name="compte")
     */
    public function index()
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $client = $this->getUser();
        $commandes = $this->getDoctrine()
            ->getRepository(Commande::class)
            ->findLastsByClient($client);
        if($client){ 
            return $this->render('client/index.html.twig', [
                'controller_name' => 'ClientController',
                'client' => $client,
                'commandes' => $commandes,
            ]);
        }
        throw $this->createNotFoundException('Utilisateur null');
    }


    /**
     * @Route("/compte/edit", name="compte_edit")
     */
    public function compteEdit(Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $client = $this->getUser();
        if($client){
            $form = $this->createForm(EditClientType::class, $client);
    
            $form->handleRequest($request);
    
            if($form->isSubmitted() && $form->isValid()){

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($client);
                $entityManager->flush();
    
                return $this->redirectToRoute('compte');
            }

            return $this->render('client/edit.html.twig', [
                'controller_name' => 'ClientController',
                'form' => $form->createView(),
            ]);
        }
        throw $this->createNotFoundException('Utilisateur null');
    }

    /**
     * @Route("/compte/commandes", name="compte_commandes")
     */
    public function commandes()
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $client = $this->getUser();
        if($client){
            
            $commandes = $this->getDoctrine()
                ->getRepository(Commande::class)
                ->findByClient($client);
               
            return $this->render('client/commandes.html.twig', [
                'controller_name' => 'ClientController',
                'commandes' => $commandes
            ]);
        }
        throw $this->createNotFoundException('Utilisateur null');
    }

    /**
     * @Route("/compte/commandes/{id}", name="compte_commande_show")
     */
    public function commandes_show($id)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $client = $this->getUser();
        if($client){
            $commande = $this->getDoctrine()
                ->getRepository(Commande::class)
                ->find($id);
                
            if($commande->getClient() == $client){
                return $this->render('client/commande_show.html.twig', [
                    'controller_name' => 'ClientController',
                    'commande' => $commande
                ]);
            }
        }
        throw $this->createNotFoundException('Utilisateur null');
    }

    /**
     * @Route("/compte/adresses/new", name="compte_adresse_new")
     */
    public function adresse_new(Request $request, EntityManagerInterface $entityManager)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $client = $this->getUser();
        if($client){
            $adresse = new Adresse();

            $form = $this->createForm(AdresseType::class, $adresse);
    
            $form->handleRequest($request);
    
            if($form->isSubmitted() && $form->isValid()){
    
                $adresse->setClient($client);
                $entityManager->persist($adresse);
                $entityManager->flush();
    
                return $this->redirectToRoute('compte');
            }

            return $this->render('client/adresse_new.html.twig', [
                'controller_name' => 'ClientController',
                'form' => $form->createView(),
            ]);
        }
        throw $this->createNotFoundException('Utilisateur null');
    }

    /**
     * @Route("/compte/adresses/{id}/edit", name="compte_adresse_edit")
     */
    public function adresse_edit($id, Request $request, EntityManagerInterface $entityManager)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $client = $this->getUser();
        if($client){
            $adresse = $entityManager->getRepository(Adresse::class)
                ->find($id);
            if($adresse && $adresse->getClient() === $client){
                $form = $this->createForm(AdresseType::class, $adresse);
        
                $form->handleRequest($request);
        
                if($form->isSubmitted() && $form->isValid()){
        
                    $adresse->setClient($client);
                    $entityManager->persist($adresse);
                    $entityManager->flush();
        
                    return $this->redirectToRoute('compte');
                }

                return $this->render('client/adresse_new.html.twig', [
                    'controller_name' => 'ClientController',
                    'form' => $form->createView(),
                ]);
            }
            throw $this->createNotFoundException('Adresse null ou n\'appartenant pas a l\'utilisateur');
        }
        throw $this->createNotFoundException('Utilisateur null');
    }
    
    /**
     * @Route("/compte/adresses/{id}/remove", name="compte_adresse_remove")
     */
    public function adresse_remove($id)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $client = $this->getUser();
        if($client){
            $em = $this->getDoctrine()
                ->getManager();
            $adresse = $em->getRepository(Adresse::class)
                ->find($id);
            
            $commande = $em->getRepository(Commande::class)
                ->findByAdresse($adresse);
                
            if($adresse->getClient() == $client){

                if(empty($commande)){
                    $em->remove($adresse);
                }else{
                    $adresse->setClient(null);
                    $em->persist($adresse);
                }
                $em->flush();

                return $this->redirectToRoute('compte');
            }
        }
        throw $this->createNotFoundException('Utilisateur null');
    }
}

templates/client/adresse_new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block stylesheets %}
    <link href="{{ asset('css/inscription.css') }}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block body %}
    {{ form_start(form , {'attr': {'class': 'form-container col-md-6 col-sm-12 col-6'}}) }}
    {{ form_row(form.adresse, {'attr': {'class': 'form-group form-control'}}) }}
    {{ form_row(form.ville, {'attr': {'class': 'form-group form-control'}}) }}
    {{ form_row(form.cp, {'attr': {'class': 'form-group form-control'}}) }}
    {{ form_row(form.pays, {'attr': {'class': 'form-group form-control'}}) }}
    {{ form_row(form.tel, {'attr': {'class': 'form-group form-control'}}) }}
    {{ form_end(form) }}
{% endblock %}

templates/client/commande_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block stylesheets %}<link rel="stylesheet" href="/css/commandeShow.css"/>{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
                <div class="lignes_commandes row">
                    {% for ligneDeCommande in commande.getLignesDeCommande %}

                        <div class="id-commande col">N°{{ commande.id }}</div>
                        <div class="libelle-article-ligne-de-commande col">{{ ligneDeCommande.article.libelle }}</div>
                        <div class="col">{{ ligneDeCommande.taille.libelle }}</div>
                        <div class="col">x{{ ligneDeCommande.qte }}</div>
                        <div class="col">{{ ligneDeCommande.getMontant }}$</div>
                        <div class="w-100"></div>

                    {% endfor %}

                    <div class="date-commande col ">Le {{ commande.date|date('d/m/Y') }}</div>
                    <div class="adresse-commande col-6">{{ commande.adresse.adresse ~ " " ~ commande.adresse.cp ~ " " ~ commande.adresse.ville}}</div>
                    <div class="articles-commande col">{{ commande.getNbArticles }} Article(s)</div>

                    <div class="w-100"></div>
                    <div class="montant-commande col offset-9">Total: {{ commande.getPrixTotal }}$</div>
                    <div class="w-100"></div>
                    <div class="status-commande col offset-9">{{ commande.statutCommande.libelle }}</div>

                </div>


            {% if commande.statutCommande.code == 1 or commande.statutCommande.code == 9 %}
                <button class="btn-payer btn btn-dark" onclick="{window.location='{{ path("payment",{commandeId: commande.id}) }}'}">Payer</button>
            {% endif %}
        </div>
    </div>





{% endblock %}

templates/client/commandes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block stylesheets %}<link rel="stylesheet" href="/css/commande.css"/>{% endblock %}

{% block body %}

    <table class="table table-striped table-hover">
        <tbody>
        {% for commande in commandes %}
            <tr class="commande" onClick={window.location="{{ path('compte_commande_show', {id: commande.id}) }}"}>
                <td class="id-commande">N°{{ commande.id }}</td>
                <td class="date-commande">Le {{ commande.date|date('d/m/Y') }}</td>
                <td class="articles-commande">{{ commande.getNbArticles }} Article(s)</td>
                <td class="montant-commande">{{ commande.getPrixTotal }}$</td>
                <td class="status-commande">{{ commande.statutCommande.libelle }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link href="{{ asset('css/inscription.css') }}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block title %}Log in!{% endblock %}

{% block body %}
    {% for message in app.flashes('user-error') %}
        <div class="flash-user-error">
            {{ message }}
        </div>
    {% endfor %}
    {{ form_start(form , {'attr': {'class': 'form-container col-md-6 col-sm-12 col-6'}}) }}
        {{ form_row(form.nom, {'attr': {'class': 'form-group form-control'}}) }}
        {{ form_row(form.prenom, {'attr': {'class': 'form-group form-control'}}) }}
    {{ form_end(form) }}
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block stylesheets %}<link rel="stylesheet" href="/css/compte.css"/>{% endblock %}

{% block body %}
<h2 class="text-uppercase">Mon Compte</h2>
<div class="container">
    <h3>Mes Informations</h3>
    <div class="infos-client">
        <div>{{ client.nom }} {{ client.prenom }}</div>
        <div>{{ client.email }}</div>
        <a href="{{ path('compte_edit') }}">Modifier</a><br>
        <a href="{{ path('compte_edit_pwd') }}">Modifier mot de passe</a>
    </div>

    <h3>Mes Adresses</h3>
    <table class="table table-striped adresses-client">
        <tbody>
            {% for adresse in client.adresses %}
                <tr>
                    <td class="adresse-adresse">{{ adresse.adresse }}</td>
                    <td class="cp-adresse">{{ adresse.cp }}</td>
                    <td class="ville-adresse">{{ adresse.ville }}</td>
                    <td class="pays-adresse">{{ adresse.pays }}</td>
                    <td class="tel-adresse">{{ adresse.tel }}</td>
                    <td><a href="{{ path('compte_adresse_remove', {id: adresse.id}) }}"><i class="fas fa-trash-alt"></i></a></td>
                    <td><a href="{{ path('compte_adresse_edit', {id: adresse.id}) }}"><i class="fas fa-edit"></i></a></td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <td class="ajouter-adresse" onClick={window.location="{{ path('compte_adresse_new') }}"}>Nouvelle Adresse</td>
        </tfoot>
    </table>


    <h3>Mes commandes</h3>
    <table class="table table-striped commandes-client table-hover">
       <tbody>
            {% for commande in commandes %}
                <tr class="commande" onClick={window.location="{{ path('compte_commande_show', {id: commande.id}) }}"}>
                    <td class="id-commande">N°{{ commande.id }}</td>
                    <td class="date-commande">Le {{ commande.date|date('d/m/Y') }}</td>
                    <td class="articles-commande">{{ commande.getNbArticles }} Article(s)</td>
                    <td class="montant-commande">{{ commande.getPrixTotal }}$</td>
                    <td class="status-commande">{{ commande.statutCommande.libelle }}</td>
                </tr>
            {% endfor %}
       </tbody>
       <tfoot>
            <td onClick={window.location="{{ path('compte_commandes') }}"}>Voir toutes mes commandes</td>
       </tfoot>
    </table>
</div>
{% endblock %}