src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_u;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeArticle", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_article;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Section", inversedBy="articles")
     */
    private $sections;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\QuantiteTaille", mappedBy="article", cascade={"persist"})
     */
    private $quantite_tailles;

    public function __construct()
    {
        $this->sections = new ArrayCollection();
        $this->lignes_de_commande = new ArrayCollection();
        $this->quantite_tailles = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixU(): ?float
    {
        return $this->prix_u;
    }

    public function setPrixU(float $prix_u): self
    {
        $this->prix_u = $prix_u;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTypeArticle(): ?TypeArticle
    {
        return $this->type_article;
    }

    public function setTypeArticle(?TypeArticle $type_article): self
    {
        $this->type_article = $type_article;

        return $this;
    }

    /**
     * @return Collection|Section[]
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): self
    {
        if (!$this->sections->contains($section)) {
            $this->sections[] = $section;
        }

        return $this;
    }

    public function removeSection(Section $section): self
    {
        if ($this->sections->contains($section)) {
            $this->sections->removeElement($section);
        }

        return $this;
    }

    /**
     * @return Collection|QuantiteTaille[]
     */
    public function getQuantiteTailles(): Collection
    {
        return $this->quantite_tailles;
    }

    public function addQuantiteTaille(QuantiteTaille $quantite_tailles): self
    {
        if (!$this->quantite_tailles->contains($quantite_tailles)) {
            $this->quantite_tailles[] = $quantite_tailles;
            $quantite_tailles->setArticle($this);
        }

        return $this;
    }

    public function removeQuantiteTaille(QuantiteTaille $quantite_tailles): self
    {
        if ($this->quantite_tailles->contains($quantite_tailles)) {
            $this->quantite_tailles->removeElement($quantite_tailles);
            // set the owning side to null (unless already changed)
            if ($quantite_tailles->getArticle() === $this) {
                $quantite_tailles->setArticle(null);
            }
        }

        return $this;
    }

}

src/Entity/Categorie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategorieRepository")
 */
class Categorie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TypeArticle", mappedBy="categorie")
     */
    private $types_articles;


    public function __construct()
    {
        $this->types_articles = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * @return Collection|TypeArticle[]
     */
    public function getTypesArticles(): Collection
    {
        return $this->types_articles;
    }

    public function addTypesArticle(TypeArticle $typesArticle): self
    {
        if (!$this->types_articles->contains($typesArticle)) {
            $this->types_articles[] = $typesArticle;
            $typesArticle->setCategorie($this);
        }

        return $this;
    }

    public function removeTypesArticle(TypeArticle $typesArticle): self
    {
        if ($this->types_articles->contains($typesArticle)) {
            $this->types_articles->removeElement($typesArticle);
            // set the owning side to null (unless already changed)
            if ($typesArticle->getCategorie() === $this) {
                $typesArticle->setCategorie(null);
            }
        }

        return $this;
    }


}

src/Form/ArticleType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Section;
use App\Entity\QuantiteTaille;
use App\Entity\TypeArticle;
use App\Form\QuantiteTailleType;

class ArticleType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder
        ->add('libelle', TextType::class, [
          'attr' => [
            'placeholder' => 'Nouvel Article',
          ]
        ])
        ->add('description', TextType::class, [
          'attr' => [
            'placeholder' => 'Nouvel Article Tendance',
          ]
        ])
        ->add('prix_u', NumberType::class, [
          'attr' => [
            "min"  => 0.01,
            'precision' => 2,
            'max' => 999,
            'step' => 0.01,
            'placeholder' => 19.99,
          ],
          'html5' => true,
        ])
        ->add('image', TextType::class, [
          'attr' => [
            'placeholder' => '/img/example.png',
          ]
        ])
        ->add('type_article', EntityType::class,[
          'class' => TypeArticle::class,
          'choice_label' => function ($entityType) {
              return $entityType->getLibelle();
          }
        ])
        ->add('sections', EntityType::class,[
          'class' => Section::class,
          'multiple' => true,
          'choice_label' => function ($section) {
              return $section->getLibelle();
          }
        ])
        ->add('quantite_tailles', CollectionType::class,[
          'entry_type' => QuantiteTailleType::class,
          'entry_options' => ['label' => false],
          'allow_add' => true,
          'allow_delete' => true,
        ])
        ->add('save', SubmitType::class);
  }

  public function configureOptions(OptionsResolver $resolver)
  {
    $resolver->setDefaults(array(
      'data_class' => 'App\Entity\Article'
    ));
  }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Article;
use App\Entity\Taille;
use App\Entity\TypeArticle;
use App\Entity\Categorie;
use App\Entity\Section;
use App\Entity\QuantiteTaille;
use App\Form\ArticleType;

class ArticleController extends AbstractController
{
    /**
     * @Route("/article", name="article")
     */
    public function index(Request $request)
    { 
        $parameters = $request->query->all();

        $page = 1;
        if(isset($parameters['page'])){
            $page = $parameters['page'];
        }

        $nbMaxParPage = 20;
        if(isset($parameters['nb_max_par_page'])){
            $nbMaxParPage = $parameters['nb_max_par_page'];
        }


        $articles = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findByParametersPagine($page, $nbMaxParPage, $parameters);

        $indexParam = 0;
        $parametres = count($parameters) > 0 ? "?" : "";
        foreach($parameters as $param => $value ){
            if($param != 'page'){
                if(is_array($value)){
                    foreach($value as $val){
                        $parametres .= ($indexParam > 0 ? "&" : "") . $param . "[]=" . $val;
                        $indexParam++;
                    }
                }else{
                    $parametres .= ($indexParam > 0 ? "&" : "") . $param . "=" . $value;
                    $indexParam++;
                }
            }
        }

        $pagination = [
            'page' => $page,
            'nbPages' => (ceil(count($articles) / $nbMaxParPage)),
            'params' => $parametres,
        ];

        $sections = $this->getDoctrine()
            ->getRepository(Section::class)
            ->findAll();

        $tailles = $this->getDoctrine()
            ->getRepository(Taille::class)
            ->findAll();

        $typesArticle = $this->getDoctrine()
            ->getRepository(TypeArticle::class)
            ->findAll();

        $categories = $this->getDoctrine()
            ->getRepository(Categorie::class)
            ->findAll();

        return $this->render('article/index.html.twig', [
            'controller_name' => 'ArticleController',
            'articles' => $articles,
            'sections' => $sections,
            'tailles' => $tailles,
            'categories' => $categories,
            'typesArticle' => $typesArticle,
            'pagination' => $pagination,
        ]);
    }

    /*
     * @Route("/article", name="article")
    public function index(Request $request)
    {
        $parameters = $request->query->all();
        $articles = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findByParameters($parameters);
        return $this->render('article/index.html.twig', [
            'controller_name' => 'ArticleController',
            'articles' => $articles
        ]);
    }
     */

    /**
     * @Route("/article/{id}", name="article_show", requirements={"id"="\d+"})
     */
    public function show($id)
    {
        $article = $this->getDoctrine()
            ->getRepository(Article::class)
            ->find($id);
       // dd($article->getSections());
        $articlesSimilaire = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findBySameArticles($article);
       
        return $this->render('article/show.html.twig', [
            'controller_name' => 'ArticleController',
            'article' => $article,
            'articlesSimilaire' => $articlesSimilaire
        ]);
    }


    
    /**
     * @Route("/test", name="test")
     */
    public function test()
    {
        $articles = json_decode(file_get_contents(__DIR__.'/../../articles.json'));

        $categories = [];
        $typeArticles = [];
        $sections = [];
        $tailles = [];

        foreach($articles->articles as $article){
            $art = get_object_vars($article);
            $categories[] = $art["categorie"];
            //$typeArticles[] = [$art["categorie"] => $art["type-article"]];
            $typeArticles[] = $art["categorie"].".".$art["type-article"];
            foreach($art["sections"] as $section){
                $sections[] = $section;
            }
            foreach($art["tailles"] as $taille){
                $tailles[] = $taille;
            }
        }
        
        $categories = array_unique($categories);
        $typeArticles = array_unique($typeArticles);
        $sections = array_unique($sections);
        $tailles = array_unique($tailles);



        dd([$articles,$categories,$typeArticles,$sections,$tailles]);
    }
}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticleController!{% endblock %}

{% block stylesheets %}<link rel="stylesheet" href="/css/article.css"/>{% endblock %}

{% block body %}
    <div class="container-articles">
        <div class="filtres-articles border-right">
            <div class="filtre-sections border-bottom">
                {#
                {% for section in sections %}
                    <input type="checkbox" name="sections" value="{{ section.libelle }}" id="{{ "section-" ~ section.libelle }}">
                    <label for="{{ "section-" ~ section.libelle }}">{{ section.libelle }}</label>
                {% endfor %}
                #} 


                <button class="btn " type="button" data-toggle="collapse" data-target="#collapse-section" aria-expanded="false" aria-controls="collapse-section">
                    Sections
                </button>


                <div class="collapse" id="collapse-section">
                    <div class="style">
                        {% for section in sections %}
                            <input class="round input-section" type="checkbox" name="sections" value="{{ section.libelle }}" id="{{ "section-" ~ section.libelle }}">
                            <label for="{{ "section-" ~ section.libelle }}">
                                {{ section.libelle }}
                            </label>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="filtre-categories border-bottom">
                {#
                {% for categorie in categories %}
                    <input type="checkbox" name="categorie" value="{{ categorie.libelle }}" id="{{ "categorie-" ~ categorie.libelle }}">
                    <label for="{{ "categorie-" ~ categorie.libelle }}">{{ categorie.libelle }}</label>
                {% endfor %}
                #}
                <button class="btn" type="button" data-toggle="collapse" data-target="#collapse-categories" aria-expanded="false" aria-controls="collapse-categories">
                    Categories
                </button>

                <div class="collapse" id="collapse-categories">
                    <div class="style">
                        {% for categorie in categories %}
                                <input class="input-categorie" type="checkbox" name="categorie" value="{{ categorie.libelle }}" id="{{ "categorie-" ~ categorie.libelle }}">
                    {# <input type="hidden" value="{{categorie.id}}"> #}
                            <label for="{{ "categorie-" ~ categorie.libelle }}">
                                {{ categorie.libelle }}
                            </label>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="filtre-types border-bottom">
                {#
                {% for typeArticle in typesArticle %}
                    <input type="checkbox" name="type-article" value="{{ typeArticle.libelle }}" id="{{ "type-article-" ~ typeArticle.libelle }}">
                    <label for="{{ "type-article-" ~ typeArticle.libelle }}">{{ typeArticle.libelle }}</label>
                {% endfor %}
                #}
                <button class="btn"  type="button" data-toggle="collapse" data-target="#collapse-types" aria-expanded="false" aria-controls="collapse-types">
                    Types
                </button>
                <div class="collapse" id="collapse-types">
                    <div class="style">
                    {% for categorie in categories %}
                        {% for typeArticle in categorie.typesArticles %}
                                <input class="input-type" type="checkbox" name="type-article" value="{{ typeArticle.libelle }}" id="{{ "type-" ~ typeArticle.libelle }}">
                                {# <input type="hidden" value="{{categorie.id}}"> #}
                            <label for="{{ "type-" ~ typeArticle.libelle }}">
                                {{ typeArticle.libelle }}
                            </label>
                        {% endfor %}
                    {% endfor %}
                    </div>
                </div>
            </div>

            <div class="filtre-tailles border-bottom">
                {#
                {% for taille in tailles %}
                    <input type="checkbox" name="tailles" value="{{ taille.libelle }}" id="{{ "taille-" ~ taille.libelle }}">
                    <label for="{{ "taille-" ~ taille.libelle }}">{{ taille.libelle }}</label>
                {% endfor %}
                #}
                <button class="btn" type="button" data-toggle="collapse" data-target="#collapse-tailles" aria-expanded="false" aria-controls="collapse-tailles">
                    Tailles
                </button>
                <div class="collapse" id="collapse-tailles">
                    <div class="style">
                        {% for taille in tailles %}
                                <input class="input-taille" type="checkbox" name="tailles" value="{{ taille.libelle }}" id="{{ "taille-" ~ taille.libelle }}">
                            <label for="{{ "taille-" ~ taille.libelle }}">
                                {{ taille.libelle }}
                            </label>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="filtre-prix border-bottom">
                <button class="btn" type="button" data-toggle="collapse" data-target="#collapse-prix" aria-expanded="false" aria-controls="collapse-prix">
                    Prix
                </button>
                <div class="collapse" id="collapse-prix">
                    Prix entre :
                    <div class="input-group">
                        <input type="number" class="form-control" name="prix" step="5" min="0" max="200" value="" placeholder="min" id="input-prix-min">
                        <div class="input-group-append">
                            <span class="input-group-text">$</span>
                        </div>
                    </div>
                    et
                    <div class="input-group">
                        <input type="number" class="form-control" name="prix" step="5" min="0" max="200" value="" placeholder="max" id="input-prix-max">
                        <div class="input-group-append">
                            <span class="input-group-text">$</span>
                        </div>
                    </div>
                    <button class="btn" id="filtre-prix-btn">Valider</button>
                </div>
            </div>
        </div>

        <div class="container-tri-articles">
            <div class="container-tri-top">
                <div class="tri-articles">
                    <button id="btn-tri-articles" class="btn btn-outline-dark" value="libelle.ASC">Nom<i class="fas fa-sort"></i></button>
                    <button id="btn-tri-articles" class="btn btn-outline-dark" value="prix_u.ASC">Prix<i class="fas fa-sort"></i></button>
                </div>
                <div class="btn-filtres-articles">
                    <button class="btn btn-outline-dark"><span>Cacher les tri</span><i class="fas fa-filter"></i></button>
                </div>
            </div>


            <div class="row row-cols-2 row-cols-md-3  list-articles">
                {% for article in articles %}
                    <div class="col mb-4">
                        <div class="card item-article h-100">
                            <img src="{{ article.image }}" class="card-img-top" alt="...">
                            <div class="card-body body-article">
                                <div class="card-body-top">
                                    <p class="card-title libelle-article" onClick={window.location="{{ path('article_show', {id: article.id}) }}"}>{{ article.libelle }}</p>
                                    <p class="card-price prix-article">{{ article.prixU }}€</p>
                                </div>
                                <p class="card-text description-article">{{ article.description ~ "..." }}</p>
                                <div class="card-cart">
                                    <select class="custom-select" name="taille" id="taille-article">
                                        {% for quantiteTaille in article.getQuantiteTailles %}
                                            {% if quantiteTaille.qte > 0 %}
                                                <option value="{{ quantiteTaille.taille.id }}">{{ quantiteTaille.taille.libelle }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                    <button class="btn btn-cart btn-outline-dark add-article-panier">Ajouter</button>
                                </div>
                            </div>
                            <input type="hidden" value="{{ article.id }}" id="id-article">
                        </div>
                    </div>
                {% endfor %}
            </div>


            {#
            <div class="list-articles">
                {% for article in articles %}
                    <div class="item-article">
                        <div class="body-article"  onClick={window.location="{{ path('article_show', {id: article.id}) }}"}>
                            <div class="libelle-article">{{ article.libelle }}</div>
                            <div class="image-article"><img src="{{ article.image }}"/></div>
                            <div class="description-article">{{ article.description|slice(0, 25) ~ "..." }}</div>
                            <div class="prix-article">{{ article.prixU }}$</div>
                        </div>
                        <div class="button-article">
                            <select name="taille" id="taille-article">
                                {% for quantiteTaille in article.getQuantiteTailles %}
                                    {% if quantiteTaille.qte > 0 %}
                                        <option value="{{ quantiteTaille.taille.id }}">{{ quantiteTaille.taille.libelle }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <button class="add-article-panier">Ajouter</button>
                        </div>
                        <input type="hidden" value="{{ article.id }}" id="id-article">
                    </div>
                {% endfor %}
            </div>
            #}
            <div class="pagination-articles">
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        <li class="{{ ('page-item' ~ (pagination.page > 1 ? ' active' : ' disabled'))}}">
                            <a class="page-link" href="{{ "/article" ~ (pagination.params != "" ? pagination.params : "?") ~ "&page=1" }}">Debut</a>
                        </li>
                        <li class="{{ ('page-item' ~ (pagination.page > 1 ? ' active' : ' disabled'))}}">
                            <a class="page-link" href="{{ "/article" ~ (pagination.params != "" ? pagination.params : "?") ~ "&page=" ~ (pagination.page - 1)  }}">Precedent</a>
                        </li>
                        <li class="page-item active" aria-current="page">
                            <span class="page-link">
                                {{ pagination.page }}
                                <span class="sr-only">(current)</span>
                            </span>
                        </li>
                        <li class="{{ ('page-item' ~ (pagination.page < pagination.nbPages ? ' active' : ' disabled'))}}">
                            <a class="page-link" href="{{ "/article" ~ (pagination.params != "" ? pagination.params : "?") ~ "&page=" ~ (pagination.page + 1) }}">Suivant</a>
                        </li>
                        <li class="{{ ('page-item' ~ (pagination.page < pagination.nbPages ? ' active' : ' disabled'))}}">
                            <a class="page-link" href="{{ "/article" ~ (pagination.params != "" ? pagination.params : "?") ~ "&page=" ~ (pagination.nbPages) }}">Fin</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

{% endblock %}
{% block javascripts %}<script src='js/article.js'></script>{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.libelle }}{% endblock %}

{% block stylesheets %}<link rel="stylesheet" href="/css/article_show.css"/>{% endblock %}

{% block body %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-7">
      <img class="img-fluid" src="{{ article.image }}"/>
    </div>
  <div class="col-lg-5">
    <h2 class="h2-responsive mb-1">{{ article.libelle }}</h2>
    <h3 class="h3-responsive text-right mb-3 mr-3"><strong>{{ article.prixU }} €</strong></h3>
    <div id="description mb-5">
      <h3 class="h3-responsive mb-2">Description</h3>
      <p class="text-muted font-weight-light ml-2">{{ article.description }}</p>
    </div>
    <p>Choissisez la taille</p>
    <div class="d-flex align-items-center flex-column div-tailles mb-5">
      <div id="btns_tailles" class="col-lg-6 col-sm-6 col-6 btn-group btn-group-toggle btns-taille mb-1" data-toggle="buttons">
        {% for q in article.getQuantiteTailles %}
          <label id="btn_taille" class="col-lg-4 col-sm-4 col-4 p-2 btn btn-outline-dark {{q.qte > 0 ? "" : "disabled"}}">
            <input type="radio" value="{{ q.taille.id }}" name="taille"><strong>{{ q.taille.libelle }}</strong>
          </label>
          {% if (loop.index)%3 == 0 %}
            </div>
            <div id="btns_taille" class="col-lg-6 col-sm-6 col-6 btn-group btn-group-toggle btns-taille mb-1" data-toggle="buttons">
          {% endif %}
        {% endfor %}
      </div>
    <input type="hidden" value="{{ article.id }}" id="id-article">
    </div>
  <div class="bottom">
    <button class="mb-1 btn btn-outline-dark btn-rounded add-article-panier disabled">
      <i class="fas fa-shopping-cart mr-2" aria-hidden="true"></i>Ajouter au panier
    </button>
  </div>
</div>
</div>
</div>
<h3 class="mt-5 ml-5 text-left">Articles similaires</h3>
<div class="presentoir-all">
    {% for articleSimilaire in articlesSimilaire %}
      <div class="card">
        <img src={{ articleSimilaire.image }} class="card-img-top" alt="..." draggable="false">
        <div class="card-body">
          <h5 class="card-title" onclick="{window.location='{{ path("article_show",{id: articleSimilaire.id})}}'}">{{ articleSimilaire.libelle }}</h5>
          <p class="card-text">{{ articleSimilaire.description }}</p>
        </div>
      </div>
  {% endfor %}
</div>


{% endblock %}
{% block javascripts %}<script src="/js/article_show.js"></script>{% endblock %}